## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("Weather_Database/WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Dikson,RU,73.5069,80.5464,30.34,79,100,9.35,overcast clouds
1,1,Bengkulu,ID,-3.8004,102.2655,81.54,72,62,0.94,broken clouds
2,2,Bredasdorp,ZA,-34.5322,20.0403,51.03,63,29,6.24,scattered clouds
3,3,La Ronge,CA,55.1001,-105.2842,48.45,29,40,14.97,scattered clouds
4,4,Paamiut,GL,61.9940,-49.6678,33.80,86,78,3.53,broken clouds

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is your desired minimum temperature for your trip? "))
max_temp = float(input("What is your desired maximum temperature for your trip? "))

What is your desired minimum temperature for your trip? 20
What is your desired maximum temperature for your trip? 50

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) &
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Dikson,RU,73.5069,80.5464,30.34,79,100,9.35,overcast clouds
3,3,La Ronge,CA,55.1001,-105.2842,48.45,29,40,14.97,scattered clouds
4,4,Paamiut,GL,61.9940,-49.6678,33.80,86,78,3.53,broken clouds
5,5,Sinegorye,RU,62.0788,150.4770,38.12,87,100,3.91,light rain
6,6,Bay Roberts,CA,47.5999,-53.2648,44.33,81,14,5.01,few clouds
8,8,Thompson,CA,55.7435,-97.8558,36.27,66,97,10.60,overcast clouds
11,11,Orichi,RU,58.4036,49.0572,35.98,89,100,6.71,light rain
14,14,Shemursha,RU,54.8866,47.5189,37.15,90,9,5.75,clear sky
20,20,Bluff,NZ,-46.6000,168.3333,42.80,65,83,22.82,broken clouds
27,27,Mehamn,NO,71.0357,27.8492,33.71,75,100,4.99,overcast clouds

In [5]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.isnull().sum()

City_ID                0
City                   0
Country                2
Lat                    0
Lng                    0
Max Temp               0
Humidity               0
Cloudiness             0
Wind Speed             0
Current Description    0
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df = preferred_cities_df.dropna()
clean_df

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Dikson,RU,73.5069,80.5464,30.34,79,100,9.35,overcast clouds
3,3,La Ronge,CA,55.1001,-105.2842,48.45,29,40,14.97,scattered clouds
4,4,Paamiut,GL,61.9940,-49.6678,33.80,86,78,3.53,broken clouds
5,5,Sinegorye,RU,62.0788,150.4770,38.12,87,100,3.91,light rain
6,6,Bay Roberts,CA,47.5999,-53.2648,44.33,81,14,5.01,few clouds
...,...,...,...,...,...,...,...,...,...,...
694,694,Yar-Sale,RU,66.8333,70.8333,33.82,95,100,23.51,overcast clouds
697,697,Havre-Saint-Pierre,CA,50.2334,-63.5986,40.28,78,10,8.77,clear sky
700,700,Ust-Kuyga,RU,70.0167,135.6000,34.18,100,100,3.44,overcast clouds
701,701,Viedma,AR,-40.8135,-62.9967,48.18,43,100,11.99,overcast clouds
707,707,Severo-Yeniseyskiy,RU,60.3725,93.0408,49.26,95,100,5.30,moderate rain

In [7]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Dikson,RU,30.34,overcast clouds,73.5069,80.5464,
3,La Ronge,CA,48.45,scattered clouds,55.1001,-105.2842,
4,Paamiut,GL,33.80,broken clouds,61.9940,-49.6678,
5,Sinegorye,RU,38.12,light rain,62.0788,150.4770,
6,Bay Roberts,CA,44.33,few clouds,47.5999,-53.2648,
8,Thompson,CA,36.27,overcast clouds,55.7435,-97.8558,
11,Orichi,RU,35.98,light rain,58.4036,49.0572,
14,Shemursha,RU,37.15,clear sky,54.8866,47.5189,
20,Bluff,NZ,42.80,broken clouds,-46.6000,168.3333,
27,Mehamn,NO,33.71,overcast clouds,71.0357,27.8492,

In [8]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
        
    except (IndexError):
        print("Hotel not found...Skipping.")

Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.

In [9]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df = hotel_df.loc[(hotel_df["Hotel Name"]!='')]
clean_hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
3,La Ronge,CA,48.45,scattered clouds,55.1001,-105.2842,Northland Motor Hotel
4,Paamiut,GL,33.80,broken clouds,61.9940,-49.6678,Pistut
6,Bay Roberts,CA,44.33,few clouds,47.5999,-53.2648,Stonewall Inn
8,Thompson,CA,36.27,overcast clouds,55.7435,-97.8558,Burntwood Hotel
14,Shemursha,RU,37.15,clear sky,54.8866,47.5189,"Gostinitsa ""Shemursha"""
...,...,...,...,...,...,...,...
686,Longyearbyen,SJ,28.24,broken clouds,78.2186,15.6401,"Radisson Blu Polar Hotel, Spitsbergen"
694,Yar-Sale,RU,33.82,overcast clouds,66.8333,70.8333,Yalemd
697,Havre-Saint-Pierre,CA,40.28,clear sky,50.2334,-63.5986,Auberge Niapiskau
701,Viedma,AR,48.18,overcast clouds,-40.8135,-62.9967,Hotel Cristal
707,Severo-Yeniseyskiy,RU,49.26,moderate rain,60.3725,93.0408,Aktolik

In [10]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [11]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [12]:
# 11a. Add a marker layer for each city to the map. 
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [ ]:
print(fig)